import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import Providers from './providers';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { TanstackProvider } from './components/providers/TanstackProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <main className="min-h-screen grid place-items-center bg-gradient-to-tr from-[#07b6d4] to-[#0296a2]">
            <Providers>{children}</Providers>
          </main>
        </TanstackProvider>
      </body>
    </html>
  );
}
